BEGIN;

ALTER TABLE products
ADD COLUMN IF NOT EXISTS category_id INTEGER;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM products WHERE category_id IS NULL) THEN
        IF NOT EXISTS (SELECT 1 FROM categories) THEN
            INSERT INTO categories (name, description)
            VALUES ('Uncategorized', 'Auto generated by migration');
        END IF;

        UPDATE products
        SET category_id = (SELECT id FROM categories ORDER BY id LIMIT 1)
        WHERE category_id IS NULL;
    END IF;
END $$;

ALTER TABLE products
ALTER COLUMN category_id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'products_category_id_fkey'
    ) THEN
        ALTER TABLE products
        ADD CONSTRAINT products_category_id_fkey
        FOREIGN KEY (category_id) REFERENCES categories(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);

COMMIT;
